baseURL = 'https://aspcompiler.github.io/'
DefaultContentLanguage = "en" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = 'en-us'
title = "Li Chen's blog"
copyright = "2023 Li Chen"
theme = 'diary'

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "Share my research and learning."
googleSearchCode = "b622800d93aee436f"
enableReadingTime=true

[params.utterances]
repo="aspcompiler/aspcompiler.github.io"
theme="github-light"

[[menu.main]]
url = "/about"
name = "About"
weight = 1
[[menu.main]]
url = "/posts"
name = "Posts"
weight = 2
[[menu.main]]
url = "/categories"
name = "Categories"
weight = 3
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 4
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 5
